export interface Provider {
    id: string,
    credentialingDocument: string,
    credentialingDocumentUrl: string,
    credentialId: string,
    issueDate: string,
    expiryDate: string,
    contactPersonName: string,
    contactPersonPhone: string,
    contactPersonEmail: string,
    contactPersonRole: string,
    region: string,
    district: string,
    gpsCoordinates: string,
    physicalAddress: string,
    digitalAddress: string,
    facilityName: string,
    facilityId: string,
    facilityType: string,
    prescribingLevel: string,
    phoneNumber: string,
    email: string,
    status: string,
    createdAt: string,
    updatedAt: string
}