export const enum ViewState {
    NHIS_DETAILS = "NHIS_DETAILS",
    INSTRUCTIONS = "INSTRUCTIONS",
    CAPTURE = "CAPTURE",
    VERIFICATION_SUCCESS = "VERIFICATION_SUCCESS",
    VERIFICATION_FAILED = "VERIFICATION_FAILED",
    VERIFICATION_SELECTION = "VERIFICATION_SELECTION"
}