export const enum ViewState {
    NHIS_DETAILS = "NHIS_DETAILS",
    INSTRUCTIONS = "INSTRUCTIONS",
    CAPTURE = "CAPTURE",
    VERIFICATION_SUCCESS = "VERIFICATION_SUCCESS",
    VERIFICATION_FAILED = "VERIFICATION_FAILED",
    VERIFICATION_SELECTION = "VERIFICATION_SELECTION"
}

export const enum DispositionViewState {
    NHIS_DETAILS = "NHIS_DETAILS",
    SELECT_DISPOSITION = "SELECT_DISPOSITION",
    INSTRUCTIONS = "INSTRUCTIONS",
    CAPTURE = "CAPTURE",
    VERIFICATION_SUCCESS = "VERIFICATION_SUCCESS",
    VERIFICATION_FAILED = "VERIFICATION_FAILED",
}